feat: add manifest example yaml file
kubernetes-sigs/obscli pull request #4
Opened 2024-05-25 08:16 UTC by nitishfy

- Add the manifest example to highlight how the example manifest will look like for OBS

2024-05-25 08:16 UTC, nitishfy commented
/assign @xmudrii

2024-05-25 12:22 UTC, cpanato requested changes

2024-05-25 12:22 UTC, cpanato commented on example.yaml
> +          -
Is this expected?

2024-05-25 12:22 UTC, cpanato commented on example.yaml
> +          - userid: sagrunert
I wpuld add fake usernames

2024-05-25 12:22 UTC, cpanato commented on example.yaml
> +                      disable: {}
Nit: new line

2024-05-28 15:06 UTC, nitishfy commented on example.yaml
> +          - userid: sagrunert
I thought of creating a real manifest that would match how our actual manifest content would look like.

2024-05-28 15:06 UTC, nitishfy commented on example.yaml
> +          -
ah no, these can be omitted.

2024-06-02 07:44 UTC, nitishfy commented on example.yaml
> +                      disable: {}
done

2024-10-30 09:57 UTC, nitishfy commented
/reopen

2024-11-29 10:53 UTC, closed without merging